# Generated by Django 4.2.17 on 2025-01-27 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_created_on_reservation_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email_address',
            field=models.EmailField(default='default@example.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(default='DefaultFirstName', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(default='DefaultLastName', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default='+0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
