# Generated by Django 4.2.17 on 2025-01-28 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_email_address_reservation_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='has_discount',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email_address',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.DeleteModel(
            name='Boat',
        ),
    ]
