# Generated by Django 4.2.17 on 2025-01-28 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0005_remove_reservation_boat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
